version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: principal-bot
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
  
  redis:
    image: "redis:alpine"
    container_name: principal-bot-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: